version: "3.8"

services:
  app1: &app1
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    environment: &env_app1
      PORT: 9997
      DATABASE_NAME: rinha
      DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432
      GIN_MODE: release
      # GOGC: 100
      # GOMEMLIMIT: 450MiB
      # GOMAXPROCS: 1
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy
    command: ["migrate_and_release"]
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.5GB'

  app2:
    <<: *app1
    depends_on:
    - app1
    environment:
      <<: *env_app1
      PORT: 9998
      RELEASE_NODE: app2@127.0.0.1
    command: ["release"]

  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    network_mode: host
    depends_on:
    - app1
    - app2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    network_mode: host
    volumes:
    - ./postgresql.conf:/etc/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '1.5GB'
