version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    environment:
      DATABASE_HOST: localhost
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: rinha
      DATABASE_POOL: 20
      PORT: 9999
      GIN_MODE: release
      GOGC: off
      GOMEMLIMIT: 1GiB
      GOMAXPROCS: 1
    network_mode: host
    depends_on:
    - postgres
    command: ["migrate_and_release"]
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1.5GB'

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    network_mode: host
    volumes:
    - ./postgresql.conf:/etc/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.5GB'
